import { Routes } from '@angular/router';
import { Home } from '../components/home/home';
import { Admin } from '../components/admin/admin';
import { SubscriptionConcerts } from '../components/subscription-concerts/subscription-concerts';
import { AllEvents } from '../components/all-events/all-events';
import { NewcomerGuide } from '../components/newcomer-guide/newcomer-guide';
import { Education } from '../components/education/education';
import { SupportYourSymphony } from '../components/support-your-symphony/support-your-symphony';
import { HistoryAndMission } from '../components/history-and-mission/history-and-mission';
import { MusicDirector } from '../components/music-director/music-director';
import { PersonnelPage } from '../components/personnel/personnel';
import { CareerOpportunities } from '../components/career-opportunities/career-opportunities';
import { BoardOfDirectors } from '../components/board-of-directors/board-of-directors';
import { SeasonSponsors } from '../components/season-sponsors/season-sponsors';
import { ConcertHall } from '../components/concert-hall/concert-hall';

export const routes: Routes = [
    { path: '', component: Home },
    { path: 'admin', component: Admin },
    { path: 'subscription-concerts', component: SubscriptionConcerts },
    { path: 'all-events', component: AllEvents },
    { path: 'newcomer-guide', component: NewcomerGuide },
    { path: 'education', component: Education },
    { path: 'support-your-symphony', component: SupportYourSymphony },
    { path: 'history-and-mission', component: HistoryAndMission },
    { path: 'music-director', component: MusicDirector },
    { path: 'staff-and-musicians', component: PersonnelPage },
    { path: 'career-opportunities', component: CareerOpportunities },
    { path: 'board-of-directors', component: BoardOfDirectors },
    { path: 'season-sponsors', component: SeasonSponsors },
    { path: 'concert-hall', component: ConcertHall }
];
